#!/usr/bin/env node
// Buyer setup wizard (P51). Collects brand/feature preferences and writes a
// .env.local (without clobbering an existing one) plus prints next steps.
// Run: npm run setup
import { createInterface } from "node:readline";
import { writeFileSync, existsSync, appendFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const ENV_PATH = join(ROOT, ".env.local");

const questions = [
  { key: "VITE_BRAND_NAME", label: "Brand name", fallback: "NeonBet" },
  { key: "VITE_SUPPORT_EMAIL", label: "Support email", fallback: "support@example.com" },
  { key: "VITE_SITE_URL", label: "Public site URL", fallback: "https://example.com/" },
  { key: "VITE_META_TITLE", label: "Meta title", fallback: "NeonBet Casino" },
  {
    key: "VITE_META_DESCRIPTION",
    label: "Meta description",
    fallback: "Mobile-first crypto casino lobby with a free $100 sign-up bonus, 300% welcome match, 10x rollover, and manual account verification.",
  },
  { key: "VITE_THEME_COLOR", label: "Theme color (hex)", fallback: "#020617" },
  { key: "VITE_SIGNUP_BONUS", label: "Sign-up bonus label", fallback: "$100" },
  { key: "VITE_MATCH_PERCENT", label: "Match percent", fallback: "300%" },
  { key: "VITE_ROLLOVER", label: "Rollover requirement", fallback: "10x" },
  { key: "VITE_VERIFICATION_FEE", label: "Verification fee label", fallback: "$75" },
  { key: "VITE_ENABLE_PROMOTIONS", label: "Enable promotions (true/false)", fallback: "true" },
  { key: "VITE_ENABLE_VERIFICATION", label: "Enable verification (true/false)", fallback: "true" },
  { key: "VITE_ENABLE_ADMIN", label: "Enable admin (true/false)", fallback: "true" },
  { key: "VITE_TELEGRAM_URL", label: "Telegram support URL (optional)", fallback: "" },
  { key: "VITE_WHATSAPP_URL", label: "WhatsApp support URL (optional)", fallback: "" },
  { key: "VITE_APP_MODE", label: "App mode (demo/supabase)", fallback: "demo" },
];

const answers = {};

function ask(i) {
  if (i >= questions.length) {
    finish();
    return;
  }
  const q = questions[i];
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  rl.question(`${q.label} [${q.fallback}]: `, (value) => {
    rl.close();
    answers[q.key] = (value || "").trim() || q.fallback;
    ask(i + 1);
  });
}

function finish() {
  const lines = Object.entries(answers).map(([k, v]) => `${k}=${v}`);
  const content = `# Generated by npm run setup — edit freely. Safe to commit a .env.local template, not secrets.\n${lines.join("\n")}\n`;

  if (existsSync(ENV_PATH)) {
    appendFileSync(ENV_PATH, `\n# --- appended by setup wizard ---\n${lines.join("\n")}\n`);
    console.log(`\nUpdated existing ${ENV_PATH} (appended new values).`);
  } else {
    writeFileSync(ENV_PATH, content);
    console.log(`\nWrote ${ENV_PATH}`);
  }

  console.log("\nNext steps:");
  console.log("  1. (Supabase mode only) set VITE_SUPABASE_URL / VITE_SUPABASE_ANON_KEY in .env.local");
  console.log("  2. (Supabase mode only) apply supabase/migrations/*.sql to your project, then create first admin:");
  console.log("       update public.profiles set role = 'admin' where email = 'you@example.com';");
  console.log("  3. Add your logo at public/brand/logo.svg (falls back to the brand short-name if missing).");
  console.log("  4. npm run dev   # demo works immediately");
  console.log("  5. npm run build && npm run preview");
}

console.log("=== NeonBet Commercial V2 — Buyer Setup Wizard ===\n");
ask(0);
